## NumPy for Machine Learning Programming Activity

In this programming activity, you will practice using NumPy, a powerful library for numerical computing, in the context of machine learning. NumPy provides efficient data structures and functions for working with arrays, which are fundamental for many machine learning tasks.

### Instructions
- For each question, write a code snippet using NumPy to solve the problem.
- Your answer should be written as a code block that demonstrates the solution.
- Additional operations beyond the discussed ones may also be useful in solving the questions.
- Feel free to refer to the NumPy documentation
- Read each question carefully and provide the code snippet that solves it.
- Test your code to ensure it produces the correct output.

### Grading
- Your code will be graded based on correctness, adherence to the instructions, and clarity of your code.
- Make sure your code is well-structured, commented, and easy to understand.
- Remember to run your code and verify the output before submitting your notebook.

### Scoring System

#### NumPy Solution:
- 3 points: The solution meets all the parameters mentioned above, demonstrating a thorough understanding and efficient use of NumPy.
- 2 points: The solution is mostly correct and adheres to the instructions, but may have minor issues or could be optimized further.
- 1 point: The solution partially meets the requirements, but there are significant issues or deviations from the instructions.
- 0 points: The solution does not address the question or provides an incorrect solution.

#### Python Solution (Deduction Points):
- Deduct 1 point from the total score, regardless of correctness or code quality, if a Python solution is provided instead of a NumPy solution.

The total score for each question will be the maximum points earned in either the NumPy solution category or the Python solution category. If a NumPy solution is provided, the deduction points will not be applied.

Answer each question with the appropriate code snippet using NumPy operations. Good luck!

In [3]:
import numpy as np

### Questions

1. Array Manipulation and Statistical Analysis:
   - Create a 2-dimensional array of shape (4, 5) with random integer values between 1 and 100. Reshape the array into a 1-dimensional array, and then find the minimum, maximum, and mean values of the reshaped array.

   Sample Output:
      ```
      5
      91
      35.35
      ```

In [4]:
# Create a 2-dimensional array
array = np.random.random((4,5))
print(f"Array: {array}")
# Reshape the array into a 1-dimensional array
reshaped_array = array.reshape(-1)

# Find the minimum, maximum, and mean values
min_value = np.min(reshaped_array)
max_value = np.max(reshaped_array)
mean_value = np.mean(reshaped_array)

print(min_value)
print(max_value)
print(mean_value)

Array: [[2.67496492e-01 3.55474677e-01 1.59312868e-02 7.96833783e-01
  8.39917274e-04]
 [4.59692881e-01 8.04624580e-01 2.68861088e-01 8.09269202e-01
  6.92048159e-01]
 [6.53465320e-01 9.20487405e-01 5.47480990e-01 5.79860216e-01
  7.83843094e-01]
 [4.12208305e-01 9.17804931e-01 8.07312136e-01 6.91403105e-03
  6.87214747e-01]]
0.0008399172743615013
0.9204874052759338
0.5393831621207632


2. Array Concatenation and Filtering:
   - Generate a random 1-dimensional array of size 10 with values between 1 and 50. Create a new array by concatenating the original array with an array of zeros of the same size. Filter out all values greater than 30 from the new array.

   Sample Output:
   ```
   [29  7 20 29  0  0  0  0  0  0  0  0  0  0]
   ```

In [5]:
# Generate a random 1-dimensional array
array = np.random.randint(1, 51, size=10)

# Concatenate the original array with an array of zeros
zeros_array = np.zeros(10, dtype=int)
concatenated_array = np.concatenate((array, zeros_array))

# Filter out values greater than 30
filtered_array = concatenated_array[concatenated_array <= 30]

print(filtered_array)

[12 28 26 24  6  4  0  0  0  0  0  0  0  0  0  0]


3. Array Manipulation and Indexing:
   - Create a 2-dimensional array of shape (3, 4) with random integer values between 1 and 10. Reshape the array into a 1-dimensional array, and then find the indices of the top three maximum values in the reshaped array.

   Sample Output:
   ```
   [ 5 11  7]
   ```

In [8]:
# Create a 2-dimensional array
array = np.random.randint(1, 11, size=(3,4))

# Reshape the array into a 1-dimensional array
reshaped_array = array.reshape(-1)

# Find the indices of the top three maximum values
# Used np.argsort to get the indices that would sort the array, and then pick the last three indices for the top three maximum values
indices = np.argsort(reshaped_array)[-3:]

print(reshaped_array, indices)

[2 6 4 3 8 4 2 6 7 7 9 6] [ 9  4 10]


4. Array Functions and Indexing:
   - Generate a random 2-dimensional array of shape (5, 5) with values between 1 and 100. Find the unique elements in the array and then retrieve the indices of all occurrences of the minimum value.

   Sample Output:
   ```
   [ 1  2 14 15 17 21 23 24 27 28 31 34 35 37 44 48 58 59 60 72 81 84 89 92
   94]
   (array([0], dtype=int64), array([1], dtype=int64))
   ```

In [16]:
# Generate a random 2-dimensional array
array = np.random.randint(1,101, size=(5,5))

# Find the unique elements
unique_elements = np.unique(array)

# Retrieve the indices of all occurrences of the minimum value
min_value = np.min(unique_elements)
min_value_indices = np.where(array == min_value)
min_value_coordinates = list(zip(min_value_indices[0], min_value_indices[1]))
print(unique_elements)
print(min_value_indices)

[ 4 11 12 18 24 31 38 43 44 45 50 54 55 61 62 75 80 82 84 90 98 99]
(array([2, 4], dtype=int64), array([4, 1], dtype=int64))


5. Array Operations and Slicing:
   - Create a 2-dimensional array of shape (6, 6) with random integer values between 1 and 100. Calculate the sum of each row and retrieve the row with the maximum sum.

   Sample Output:
   ```
   [70 57 67 98 56 73]
   ```

In [21]:
# Create a 2-dimensional array
array = np.random.randint(1,101, size=(6,6))
print(array)
# Calculate the sum of each row
row_sums = np.sum(array, axis=1)

# Retrieve the row with the maximum sum
max_index = np.argmax(row_sums)
max_sum_row = array[max_index]
print("Row with max sum:", max_sum_row)

[[73 44 77  1 67 16]
 [68 52 40 49 32 24]
 [51 19 22 54  5 89]
 [29 50 49 42 77 14]
 [ 9 58 94 96 34 41]
 [79  5 51 56 44 70]]
Row with max sum: [ 9 58 94 96 34 41]


6. Array Generation and Filtering:
   - Generate a random 1-dimensional array of size 20 with values between 1 and 100. Create a new array by replacing all even values in the original array with zeros.

   Sample Output:
   ```
   [51 81 59  0  0  0 67  0  0 27 95 49  0 13  3 17  0 87 69 61]
   ```

In [22]:
# Generate a random 1-dimensional array
array = np.random.randint(1, 101, size=20)
print(array)

# Replace all even values with zeros
filtered_array = np.where(array % 2 == 0, 0, array)

print(filtered_array)

[ 8  2 84 97 38 90 14 18 55 27  4 53 21 60 24 95 55 29 46  1]
[ 0  0  0 97  0  0  0  0 55 27  0 53 21  0  0 95 55 29  0  1]


7. Broadcasting and Element-wise Operations:
   - Create a 2-dimensional array of shape (3, 3) with random integer values between 1 and 10. Multiply each element in the array by a scalar value of 2.

   Sample Output:
   ```
   [[14 16  6]
    [ 6 10  8]
    [12  8  4]]
   ```

In [25]:
# Create a 2-dimensional array
array = np.random.randint(1, 11, size=(3,3))
print(array)

# Multiply each element by a scalar value of 2
multiplied_array = array * 2

print(multiplied_array)

[[ 5  9  5]
 [ 7  6 10]
 [ 3 10 10]]
[[10 18 10]
 [14 12 20]
 [ 6 20 20]]


8. Array Sorting and Ranking:
   - Generate a random 1-dimensional array of size 10 with values between 1 and 100. Sort the array in descending order, and retrieve the indices that would sort the array in ascending order.

   Sample Output:
   ```
   [99 95 78 67 65 61 32 28  7  1]
   [4 0 1 7 3 2 6 9 5 8]
   ```

In [27]:
# Generate a random 1-dimensional array
array = np.random.randint(1, 100, size=10)

# Sort the array in descending order
sorted_descending_array = np.sort(array)[::-1]

# Retrieve the indices that would sort the array in ascending order
ascending_indices = np.argsort(array) 

print(sorted_descending_array)
print(ascending_indices)

[90 54 52 49 47 33 25 19 15  6]
[2 7 6 3 0 8 1 5 9 4]


9. Array Reshaping and Broadcasting:
   - Create a 1-dimensional array with values from 1 to 12. Reshape the array into a 2-dimensional array of shape (3, 4). Create a 1-dimensional array of shape (3, 1) with values [1, 2, 3]. Add the 1-dimensional array to each column of the reshaped array.

   Sample Output:
   ```
   [[ 2  3  4  5]
    [ 7  8  9 10]
    [12 13 14 15]]
   ```

In [29]:
# Create a 1-dimensional array
array = np.arange(1,13)

# Reshape the array into a 2-dimensional array
reshaped_array = array.reshape(3,4)

# Create a 1-dimensional array to be added to each column
addition_array = np.array([1, 2, 3]).reshape(3, 1)

# Add the 1-dimensional array to each column
result_array = reshaped_array + addition_array

print(result_array)

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


10. Logical Operations and Indexing:
    - Generate a random 1-dimensional array of size 10 with values between 0 and 1. Create a new array by replacing values greater than 0.5 with 1 and values less than or equal to 0.5 with 0.

    Sample Output:
    ```
    [1 1 0 0 1 1 0 1 0 1]
    ```

In [30]:
# Generate a random 1-dimensional array
array = np.random.rand(10)
print(array)

# Create a new array with values replaced by 0 or 1
new_array = np.where(array > 0.5, 1, 0)

print(new_array)

[0.78553879 0.02707079 0.30650075 0.87704574 0.98210929 0.73498659
 0.72268379 0.50908197 0.23564669 0.91467334]
[1 0 0 1 1 1 1 1 0 1]
