## NumPy for Machine Learning Programming Activity

In this programming activity, you will practice using NumPy, a powerful library for numerical computing, in the context of machine learning. NumPy provides efficient data structures and functions for working with arrays, which are fundamental for many machine learning tasks.

### Instructions
- For each question, write a code snippet using NumPy to solve the problem.
- Your answer should be written as a code block that demonstrates the solution.
- Additional operations beyond the discussed ones may also be useful in solving the questions.
- Feel free to refer to the NumPy documentation
- Read each question carefully and provide the code snippet that solves it.
- Test your code to ensure it produces the correct output.

### Grading
- Your code will be graded based on correctness, adherence to the instructions, and clarity of your code.
- Make sure your code is well-structured, commented, and easy to understand.
- Remember to run your code and verify the output before submitting your notebook.

### Scoring System

#### NumPy Solution:
- 3 points: The solution meets all the parameters mentioned above, demonstrating a thorough understanding and efficient use of NumPy.
- 2 points: The solution is mostly correct and adheres to the instructions, but may have minor issues or could be optimized further.
- 1 point: The solution partially meets the requirements, but there are significant issues or deviations from the instructions.
- 0 points: The solution does not address the question or provides an incorrect solution.

#### Python Solution (Deduction Points):
- Deduct 1 point from the total score, regardless of correctness or code quality, if a Python solution is provided instead of a NumPy solution.

The total score for each question will be the maximum points earned in either the NumPy solution category or the Python solution category. If a NumPy solution is provided, the deduction points will not be applied.

Answer each question with the appropriate code snippet using NumPy operations. Good luck!

In [ ]:
%pip install numpy

In [ ]:
import numpy as np

### Questions

1. Array Manipulation and Statistical Analysis:
   - Create a 2-dimensional array of shape (4, 5) with random integer values between 1 and 100. Reshape the array into a 1-dimensional array, and then find the minimum, maximum, and mean values of the reshaped array.

   Sample Output:
      ```
      5
      91
      35.35
      ```

In [ ]:
# Create a 2-dimensional array
# array = 

# Reshape the array into a 1-dimensional array
# reshaped_array = 

# Find the minimum, maximum, and mean values
# min_value = 
# max_value = 
# mean_value = 

# print(min_value)
# print(max_value)
# print(mean_value)

2. Array Concatenation and Filtering:
   - Generate a random 1-dimensional array of size 10 with values between 1 and 50. Create a new array by concatenating the original array with an array of zeros of the same size. Filter out all values greater than 30 from the new array.

   Sample Output:
   ```
   [29  7 20 29  0  0  0  0  0  0  0  0  0  0]
   ```

In [ ]:
# Generate a random 1-dimensional array
# array = 

# Concatenate the original array with an array of zeros
# concatenated_array = 

# Filter out values greater than 30
# filtered_array = 

# print(filtered_array)

3. Array Manipulation and Indexing:
   - Create a 2-dimensional array of shape (3, 4) with random integer values between 1 and 10. Reshape the array into a 1-dimensional array, and then find the indices of the top three maximum values in the reshaped array.

   Sample Output:
   ```
   [ 5 11  7]
   ```

In [ ]:
# Create a 2-dimensional array
# array = 

# Reshape the array into a 1-dimensional array
# reshaped_array = 

# Find the indices of the top three maximum values
# indices = 

# print(indices)

4. Array Functions and Indexing:
   - Generate a random 2-dimensional array of shape (5, 5) with values between 1 and 100. Find the unique elements in the array and then retrieve the indices of all occurrences of the minimum value.

   Sample Output:
   ```
   [ 1  2 14 15 17 21 23 24 27 28 31 34 35 37 44 48 58 59 60 72 81 84 89 92
   94]
   (array([0], dtype=int64), array([1], dtype=int64))
   ```

In [ ]:
# Generate a random 2-dimensional array
# array = 

# Find the unique elements
# unique_elements = 

# Retrieve the indices of all occurrences of the minimum value
# indices = 

# print(unique_elements)
# print(indices)

5. Array Operations and Slicing:
   - Create a 2-dimensional array of shape (6, 6) with random integer values between 1 and 100. Calculate the sum of each row and retrieve the row with the maximum sum.

   Sample Output:
   ```
   [70 57 67 98 56 73]
   ```

In [ ]:
# Create a 2-dimensional array
# array = 

# Calculate the sum of each row
# row_sums = 

# Retrieve the row with the maximum sum
# max_sum_row = 

# print(max_sum_row)

6. Array Generation and Filtering:
   - Generate a random 1-dimensional array of size 20 with values between 1 and 100. Create a new array by replacing all even values in the original array with zeros.

   Sample Output:
   ```
   [51 81 59  0  0  0 67  0  0 27 95 49  0 13  3 17  0 87 69 61]
   ```

In [ ]:
# Generate a random 1-dimensional array
# array = 

# Replace all even values with zeros
# filtered_array = 

# print(filtered_array)

7. Broadcasting and Element-wise Operations:
   - Create a 2-dimensional array of shape (3, 3) with random integer values between 1 and 10. Multiply each element in the array by a scalar value of 2.

   Sample Output:
   ```
   [[14 16  6]
    [ 6 10  8]
    [12  8  4]]
   ```

In [ ]:
# Create a 2-dimensional array
# array = 

# Multiply each element by a scalar value of 2
# multiplied_array = 

# print(multiplied_array)

8. Array Sorting and Ranking:
   - Generate a random 1-dimensional array of size 10 with values between 1 and 100. Sort the array in descending order, and retrieve the indices that would sort the array in ascending order.

   Sample Output:
   ```
   [99 95 78 67 65 61 32 28  7  1]
   [4 0 1 7 3 2 6 9 5 8]
   ```

In [ ]:
# Generate a random 1-dimensional array
# array = 

# Sort the array in descending order
# sorted_array = 

# Retrieve the indices that would sort the array in ascending order
# ascending_indices = 

# print(sorted_array)
# print(ascending_indices)

9. Array Reshaping and Broadcasting:
   - Create a 1-dimensional array with values from 1 to 12. Reshape the array into a 2-dimensional array of shape (3, 4). Create a 1-dimensional array of shape (3, 1) with values [1, 2, 3]. Add the 1-dimensional array to each column of the reshaped array.

   Sample Output:
   ```
   [[ 2  3  4  5]
    [ 7  8  9 10]
    [12 13 14 15]]
   ```

In [ ]:
# Create a 1-dimensional array
# array = 

# Reshape the array into a 2-dimensional array
# reshaped_array = 

# Create a 1-dimensional array to be added to each column
# addition_array = 

# Add the 1-dimensional array to each column
# result_array = 

# print(result_array)

10. Logical Operations and Indexing:
    - Generate a random 1-dimensional array of size 10 with values between 0 and 1. Create a new array by replacing values greater than 0.5 with 1 and values less than or equal to 0.5 with 0.

    Sample Output:
    ```
    [1 1 0 0 1 1 0 1 0 1]
    ```

In [ ]:
# Generate a random 1-dimensional array
# array = 

# Create a new array with values replaced by 0 or 1
# new_array = 

# print(new_array)